/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  items: Array<string>;
  order?: number;
};

export type Client = {
  _id: string;
  _type: "client";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  width: number;
  height: number;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ExpertiseReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "expertise";
};

export type Expertise = {
  _id: string;
  _type: "expertise";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  subtitle: string;
  description: string;
  features?: Array<{
    title: string;
    description: string;
    _key: string;
  }>;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  related?: ExpertiseReference;
  order?: number;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  category?: Array<string>;
  publishedAt: string;
  date: string;
  readTime?: string;
  author?: AuthorReference;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: BlockContent;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category: string;
  year: string;
  layout: "landscape" | "portrait";
  aspectRatio: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  video?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description: string;
  tags?: Array<string>;
  textColor?: "white" | "black";
  featured?: boolean;
  order?: number;
  body?: BlockContent;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  tagline: string;
  description: string;
  url: string;
  introStatement: string;
  aboutHeading: string;
  aboutCopy?: Array<string>;
  aboutImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  aboutLink?: {
    label?: string;
    href?: string;
  };
  stats?: Array<{
    value: string;
    label: string;
    _key: string;
  }>;
  footerCtaLine1?: string;
  footerCtaLine2?: string;
  footerTickerWords?: Array<string>;
  footerCopyright?: string;
  nav?: Array<{
    label: string;
    href: string;
    _type: "navLink";
    _key: string;
  }>;
  workCategories?: Array<{
    label: string;
    href: string;
    slug: string;
    _key: string;
  }>;
  expertiseMenu?: Array<{
    heading: string;
    links?: Array<{
      label: string;
      href: string;
      _type: "navLink";
      _key: string;
    }>;
    _type: "expertiseGroup";
    _key: string;
  }>;
  email: string;
  locations?: Array<{
    city: string;
    country: string;
    email?: string;
    _key: string;
  }>;
  social?: {
    instagram?: string;
    linkedin?: string;
    x?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | Service
  | Client
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | ExpertiseReference
  | Expertise
  | AuthorReference
  | Article
  | Author
  | SanityFileAssetReference
  | Project
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    name,    tagline,    description,    url,    introStatement,    aboutHeading,    aboutCopy,    "aboutImage": aboutImage.asset->url,    aboutLink,    stats,    "footer": {      "ctaLine1": footerCtaLine1,      "ctaLine2": footerCtaLine2,      "tickerWords": footerTickerWords,      "copyright": footerCopyright    },    email,    locations,    social,    nav[]{ label, href },    workCategories[]{ label, href, slug },    expertiseMenu[]{ heading, links[]{ label, href } }  }
export type SETTINGS_QUERY_RESULT = {
  name: string;
  tagline: string;
  description: string;
  url: string;
  introStatement: string;
  aboutHeading: string;
  aboutCopy: Array<string> | null;
  aboutImage: string | null;
  aboutLink: {
    label?: string;
    href?: string;
  } | null;
  stats: Array<{
    value: string;
    label: string;
    _key: string;
  }> | null;
  footer: {
    ctaLine1: string | null;
    ctaLine2: string | null;
    tickerWords: Array<string> | null;
    copyright: string | null;
  };
  email: string;
  locations: Array<{
    city: string;
    country: string;
    email?: string;
    _key: string;
  }> | null;
  social: {
    instagram?: string;
    linkedin?: string;
    x?: string;
  } | null;
  nav: Array<{
    label: string;
    href: string;
  }> | null;
  workCategories: Array<{
    label: string;
    href: string;
    slug: string;
  }> | null;
  expertiseMenu: Array<{
    heading: string;
    links: Array<{
      label: string;
      href: string;
    }> | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"]|order(order asc, year desc){   "slug": slug.current,  title,  category,  year,  layout,  aspectRatio,  "image": image.asset->url,  "video": video.asset->url,  "poster": poster.asset->url,  description,  tags,  featured,  textColor }
export type PROJECTS_QUERY_RESULT = Array<{
  slug: string;
  title: string;
  category: string;
  year: string;
  layout: "landscape" | "portrait";
  aspectRatio: string;
  image: string | null;
  video: string | null;
  poster: string | null;
  description: string;
  tags: Array<string> | null;
  featured: boolean | null;
  textColor: "black" | "white" | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && featured == true]|order(order asc, year desc){   "slug": slug.current,  title,  category,  year,  layout,  aspectRatio,  "image": image.asset->url,  "video": video.asset->url,  "poster": poster.asset->url,  description,  tags,  featured,  textColor }
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  slug: string;
  title: string;
  category: string;
  year: string;
  layout: "landscape" | "portrait";
  aspectRatio: string;
  image: string | null;
  video: string | null;
  poster: string | null;
  description: string;
  tags: Array<string> | null;
  featured: true;
  textColor: "black" | "white" | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{      "slug": slug.current,  title,  category,  year,  layout,  aspectRatio,  "image": image.asset->url,  "video": video.asset->url,  "poster": poster.asset->url,  description,  tags,  featured,  textColor,    body[]{      ...,      _type == "image" => { ..., "url": asset->url }    }  }
export type PROJECT_QUERY_RESULT = {
  slug: string;
  title: string;
  category: string;
  year: string;
  layout: "landscape" | "portrait";
  aspectRatio: string;
  image: string | null;
  video: string | null;
  poster: string | null;
  description: string;
  tags: Array<string> | null;
  featured: boolean | null;
  textColor: "black" | "white" | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
        url: string | null;
      }
  > | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)]{ "slug": slug.current }
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: ARTICLES_QUERY
// Query: *[_type == "article"]|order(publishedAt desc){   "slug": slug.current,  title,  excerpt,  category,  date,  readTime,  publishedAt,  "author": author->{ name, "avatar": avatar.asset->url },  "image": image.asset->url }
export type ARTICLES_QUERY_RESULT = Array<{
  slug: string;
  title: string;
  excerpt: string;
  category: Array<string> | null;
  date: string;
  readTime: string | null;
  publishedAt: string;
  author: {
    name: string;
    avatar: string | null;
  } | null;
  image: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: ARTICLE_QUERY
// Query: *[_type == "article" && slug.current == $slug][0]{      "slug": slug.current,  title,  excerpt,  category,  date,  readTime,  publishedAt,  "author": author->{ name, "avatar": avatar.asset->url },  "image": image.asset->url,    body[]{      ...,      _type == "image" => { ..., "url": asset->url }    }  }
export type ARTICLE_QUERY_RESULT = {
  slug: string;
  title: string;
  excerpt: string;
  category: Array<string> | null;
  date: string;
  readTime: string | null;
  publishedAt: string;
  author: {
    name: string;
    avatar: string | null;
  } | null;
  image: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
        url: string | null;
      }
  > | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: ARTICLE_SLUGS_QUERY
// Query: *[_type == "article" && defined(slug.current)]{ "slug": slug.current }
export type ARTICLE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: EXPERTISE_LIST_QUERY
// Query: *[_type == "expertise"]|order(order asc){   "slug": slug.current,  title,  subtitle,  description,  features[]{ title, description },  "image": image.asset->url,  "relatedSlug": related->slug.current }
export type EXPERTISE_LIST_QUERY_RESULT = Array<{
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  features: Array<{
    title: string;
    description: string;
  }> | null;
  image: string | null;
  relatedSlug: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: EXPERTISE_QUERY
// Query: *[_type == "expertise" && slug.current == $slug][0]{   "slug": slug.current,  title,  subtitle,  description,  features[]{ title, description },  "image": image.asset->url,  "relatedSlug": related->slug.current }
export type EXPERTISE_QUERY_RESULT = {
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  features: Array<{
    title: string;
    description: string;
  }> | null;
  image: string | null;
  relatedSlug: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: EXPERTISE_SLUGS_QUERY
// Query: *[_type == "expertise" && defined(slug.current)]{ "slug": slug.current }
export type EXPERTISE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: CLIENTS_QUERY
// Query: *[_type == "client"]|order(order asc){    "id": slug.current,    name,    "logo": logo.asset->url,    width,    height  }
export type CLIENTS_QUERY_RESULT = Array<{
  id: string;
  name: string;
  logo: string | null;
  width: number;
  height: number;
}>;

// Source: sanity/lib/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"]|order(order asc){ title, items }
export type SERVICES_QUERY_RESULT = Array<{
  title: string;
  items: Array<string>;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0]{\n    name,\n    tagline,\n    description,\n    url,\n    introStatement,\n    aboutHeading,\n    aboutCopy,\n    "aboutImage": aboutImage.asset->url,\n    aboutLink,\n    stats,\n    "footer": {\n      "ctaLine1": footerCtaLine1,\n      "ctaLine2": footerCtaLine2,\n      "tickerWords": footerTickerWords,\n      "copyright": footerCopyright\n    },\n    email,\n    locations,\n    social,\n    nav[]{ label, href },\n    workCategories[]{ label, href, slug },\n    expertiseMenu[]{ heading, links[]{ label, href } }\n  }\n': SETTINGS_QUERY_RESULT;
    '\n  *[_type == "project"]|order(order asc, year desc){ \n  "slug": slug.current,\n  title,\n  category,\n  year,\n  layout,\n  aspectRatio,\n  "image": image.asset->url,\n  "video": video.asset->url,\n  "poster": poster.asset->url,\n  description,\n  tags,\n  featured,\n  textColor\n }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && featured == true]|order(order asc, year desc){ \n  "slug": slug.current,\n  title,\n  category,\n  year,\n  layout,\n  aspectRatio,\n  "image": image.asset->url,\n  "video": video.asset->url,\n  "poster": poster.asset->url,\n  description,\n  tags,\n  featured,\n  textColor\n }\n': FEATURED_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    \n  "slug": slug.current,\n  title,\n  category,\n  year,\n  layout,\n  aspectRatio,\n  "image": image.asset->url,\n  "video": video.asset->url,\n  "poster": poster.asset->url,\n  description,\n  tags,\n  featured,\n  textColor\n,\n    body[]{\n      ...,\n      _type == "image" => { ..., "url": asset->url }\n    }\n  }\n': PROJECT_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)]{ "slug": slug.current }\n': PROJECT_SLUGS_QUERY_RESULT;
    '\n  *[_type == "article"]|order(publishedAt desc){ \n  "slug": slug.current,\n  title,\n  excerpt,\n  category,\n  date,\n  readTime,\n  publishedAt,\n  "author": author->{ name, "avatar": avatar.asset->url },\n  "image": image.asset->url\n }\n': ARTICLES_QUERY_RESULT;
    '\n  *[_type == "article" && slug.current == $slug][0]{\n    \n  "slug": slug.current,\n  title,\n  excerpt,\n  category,\n  date,\n  readTime,\n  publishedAt,\n  "author": author->{ name, "avatar": avatar.asset->url },\n  "image": image.asset->url\n,\n    body[]{\n      ...,\n      _type == "image" => { ..., "url": asset->url }\n    }\n  }\n': ARTICLE_QUERY_RESULT;
    '\n  *[_type == "article" && defined(slug.current)]{ "slug": slug.current }\n': ARTICLE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "expertise"]|order(order asc){ \n  "slug": slug.current,\n  title,\n  subtitle,\n  description,\n  features[]{ title, description },\n  "image": image.asset->url,\n  "relatedSlug": related->slug.current\n }\n': EXPERTISE_LIST_QUERY_RESULT;
    '\n  *[_type == "expertise" && slug.current == $slug][0]{ \n  "slug": slug.current,\n  title,\n  subtitle,\n  description,\n  features[]{ title, description },\n  "image": image.asset->url,\n  "relatedSlug": related->slug.current\n }\n': EXPERTISE_QUERY_RESULT;
    '\n  *[_type == "expertise" && defined(slug.current)]{ "slug": slug.current }\n': EXPERTISE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "client"]|order(order asc){\n    "id": slug.current,\n    name,\n    "logo": logo.asset->url,\n    width,\n    height\n  }\n': CLIENTS_QUERY_RESULT;
    '\n  *[_type == "service"]|order(order asc){ title, items }\n': SERVICES_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
